### PR TITLE
Layout Improvements

### PR DESCRIPTION
**Pull request by marlonbernardes**
This PR improves (I hope)  the layout in several ways. While I'm not completely happy with the result (it certainly needs more color), I think it's ok for our first release. What do you think?

Some screenshots below:

image

image

Please don't merge it yet!

### CODE REVIEW

**Comment by rafaeleyng** [comment]
One thing I've noticed right away was the " | " after the last nav link on the header. Is it on purpose? You know, I mean the last-child margin 0px thing.

**Comment by rafaeleyng** [comment]
I would like some screenshot of the author page, I would like to see how you used the gravatar image.

**Comment by rafaeleyng** [comment]
Besides that, I think it is a perfectly fine first layout.

**Comment by marlonbernardes** [comment]
@rafaeleyng good catch! The border-right was removed from the last menu item!

**Comment by marlonbernardes** [comment]
@rafaeleyng I did not change the authors page yet, anyways, here is the screenshot in its current state:

image

**Comment by rafaeleyng** [comment]
@marlonbernardes I meant the page of a particular author, not the listing of all authors. But anyway, it's cool. One thing I suggest you taking care if you can is styling the translations links is some nice way.

**Pull request merged**
