### PR TITLE
Go live!

### PR DESCRIPTION
**Pull request by marlonbernardes**
Changes:
- [x] CSS files were moved to `assets/css` (to keep things organized)
- [x] `.html` extension removed from post URLs 
  - (eg.: `localhost:4000/how-to-use-axios-as-your-http-client.html` became `localhost:4000/how-to-use-axios-as-your-http-client/`)
- [x] I created a rake task (run with `rake production`) to automate deployment to production.

During this PR I also created a new bucket in Amazon's S3, set up CloudFront as our CDN and pointed the name servers for our domain to Route 53 .

Site should be online soon (click [here](http://codeheaven.io) to check), but all these DNS changes could take up to a day to take effect.

### CODE REVIEW

**Comment by dwayhs** [comment]
Octopress already has this feature :cry: 

https://github.com/octopress/octopress#amazon-s3-deployment-configuration

**Comment by marlonbernardes** [comment]
@dwayhs no worries! I'll change it in order to use octopress deploy. I didn't know that it existed - I'm only used to jekyll.

**Comment by marlonbernardes** [comment]
Done in #20.

**Comment by marlonbernardes** [comment]
Ok, this PR was reopened because the suggested way of deploying the website, `octopress deploy` does  not gzip assets natively - so it would require some tweaks to the deploy process in order for it to work effectively. Since this has already been done in this task, there is no point on using octopress deploy. All we need to do is to run `rake production`.

**Pull request merged**
